[versions]
changelog = "2.5.0"
grammarKit = "2023.3.0.3"
intelliJPlatform = "2.12.0"

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
grammarKit = { id = "org.jetbrains.grammarkit", version.ref = "grammarKit" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
